### ISSUE TITLE
Add request error handling in Python scripts

### ISSUE THREAD

**Issue by itrujnara** [nf-core/reportho#22]
### Description of feature

It's done with try-except blocks and RequestError exception type

**Comment by JoseEspinosa** [comment]
Also for these processes we could implement something such as this (in modules.config):
```groovy
withName:FOO {
        errorStrategy = 'retry'
        maxRetries    = 3
    }
```

**Comment by JoseEspinosa** [comment]
For completeness, the `FETCH_PANTHER_GROUP_ONLINE` is failing in CI quite often (seems to be in the first attempt) as shown [here](https://github.com/nf-core/reportho/actions/runs/9018253423/job/24778849854?pr=21)
