### ISSUE TITLE
Test for checking combination of parameters

### ISSUE THREAD

**Issue by luisas** [nf-core/reportho#37]
### Description of feature

We should provide a comprehensive test that checks for the main combinations of parameters, even if it is only for ourselves to make sure everything is running as expected.

We can create the matrix strategy (at least partially) as in rnaseq https://github.com/nf-core/rnaseq/blob/master/.github/workflows/ci.yml

**Comment by itrujnara** [comment]
As discussed, we already have enough test coverage (unless the reviewers ask for something specific)
