### ISSUE TITLE
Add README to reportho test-datasets

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/reportho#48]
### Description of feature

Update the `README.md` of the branch corresponding to the test-dataset repo of `reportho`, [here](https://github.com/nf-core/test-datasets/blob/reportho/README.md). The chipseq [readme](https://github.com/nf-core/test-datasets/blob/chipseq/README.md) could be used as a template.

**Comment by itrujnara** [comment]
Solved in nf-core/test-datasets#1222.
